name: daily-cron
on:
  schedule:
    - cron: '30 19 * * 0-4' # 8:30 AM NZDT Mon-Fri (UTC+13)
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - name: Run script
        run: npm run cron
